import {z} from "zod";

export const AvizareDallbogCreateSchema = z.object({
    client_id: z.uuidv4(),
    existing_damaged_vehicle: z.string(),
    claim_date: z.string(),
    claim_time: z.string(),
    claim_series: z.string(),
    claim_number: z.string(),
    claim_inspector_signature: z.string(),
    claimant_signature: z.string(),
    claimant_name: z.string(),
    claimant_father_name: z.string(),
    claimant_mother_name: z.string(),
    claimant_birth_date: z.string(),
    claimant_birth_place: z.string(),
    claimant_citizenship: z.string(),
    claimant_address: z.string(),
    claimant_cnp: z.string(),
    claimant_id_series: z.string(),
    claimant_id_number: z.string(),
    claimant_license_category: z.string(),
    claimant_license_number: z.string(),
    claimant_license_issued_by: z.string(),
    claimant_license_issued_date: z.string(),
    claimant_license_experience: z.string(),
    claimant_profession: z.string(),
    claimant_employer: z.string(),
    claimant_employer_phone: z.string(),
    incident_date: z.string(),
    incident_time: z.string(),
    vehicle_state: z.string(),
    vehicle_registration_number: z.string(),
    vehicle_make_model: z.string(),
    vehicle_color: z.string(),
    vehicle_owner: z.string(),
    incident_location: z.string(),
    incident_street: z.string(),
    incident_direction_from: z.string(),
    incident_direction_to: z.string(),
    incident_place: z.string(),
    incident_intersection: z.string(),
    incident_outside_of: z.string(),
    incident_highway: z.string(),
    vehicle_damages: z.string(),
    existing_casco: z.boolean(),
    casco_company: z.string(),
    casco_validity_end_date: z.string(),
    light_conditions: z.string(),
    road_conditions: z.string(),
    vehicle_category: z.string(),
    past_damages: z.string(),
    diagram: z.string(),
    signature: z.string(),
});

export const AvizareDallbogUpdateSchema = AvizareDallbogCreateSchema;