import {query} from "@/db";
import * as types from "@/entities/templates/avizare-axeria/types";

export async function getAllAvizareAxeria(): Promise<Array<types.AvizareAxeria>> {
    const result = await query(`
    SELECT * FROM avizare_axeria
    ORDER BY created_at DESC`);
    return result.rows;
}

export async function getAvizareAxeriaById(id: string): Promise<types.AvizareAxeria> {
    const result = await query(
        `SELECT * FROM avizare_axeria WHERE id = $1`,
        [id]
    );
    if(result.rowCount === 0) throw new Error("Avizare axerie not found");
    return result.rows[0];
}

export async function createAvizareAxeria(data: types.AvizareAxeriaCreateSchema): Promise<types.AvizareAxeria>{
    const result = await query(
        `INSERT INTO avizare_axeria (
    client_id,
    claim_number,
    existing_damage,
    inspection_date,
    vehicle_repair_authorisation_document,
    claims_inspection_signature,
    claimant_signature,
    fault_determination,
    claimant_name,
    claimant_father_name,
    claimant_mother_name,
    claimant_birth_date,
    claimant_birth_place,
    claimant_citizenship,
    claimant_address,
    claimant_cnp,
    claimant_id_series,
    claimant_id_number,
    claimant_id_issued_by,
    claimant_license_category,
    claimant_license_number,
    claimant_license_issued_by,
    claimant_license_issued_date,
    claimant_license_experience,
    claimant_profession,
    claimant_employer,
    claimant_employer_address,
    claimant_employer_phone,
    claimant_employer_email,
    claimant_policy_series,
    claimant_policy_number,
    claimant_policy_start_date,
    claimant_policy_end_date,
    incident_date,
    incident_time,
    vehicle_registration_number,
    vehicle_make,
    vehicle_model,
    vehicle_color,
    vehicle_vin,
    vehicle_owner,
    vehicle_owner_cnp,
    incident_location,
    incident_county,
    incident_street,
    incident_direction_from,
    incident_direction_to,
    incident_place,
    incident_km,
    incident_intersection,
    incident_outside_of,
    incident_highway,
    incident_damages,
    incident_deceased,
    incident_other_damages,
    incident_deceased_name,
    casco_number,
    casco_company,
    casco_validity_start_date,
    casco_validity_end_date,
    light_conditions,
    road_conditions,
    weather_conditions,
    road_surface_type,
    vehicle_category,
    vehicle_speed,
    vehicle_break_mark,
    damage_area,
    other_vehicle_damage_area,
    diagram_before,
    diagram_at_time_of_incident,
    diagram_after,
    other_victim_name,
    other_victim_address,
    other_victim_property,
    authorities_document_series,
    authorities_document_number,
    repair_authorisation_series,
    repair_authorisation_number,
    repair_authorisation_date,
    incident_responsible_name,
    incident_responsible_address,
    incident_responsible_phone,
    incident_responsible_email,
    incident_responsible_vehicle_registration_number,
    incident_responsible_vehicle_make,
    incident_responsible_vehicle_model,
    incident_responsible_vehicle_color,
    incident_responsible_rca,
    incident_responsible_rca_series,
    incident_responsible_rca_number,
    incident_responsible_rca_validity_start_date,
    incident_responsible_rca_validity_end_date,
    claim_date,
    signature,
    created_at
        )
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
        $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
        $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
        $41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
        $51,$52,$53,$54,$55,$56,$57,$58,$59,$60,
        $61,$62,$63,$64,$65,$66,$67,$68,$69,$70,
        $71,$72,$73,$74,$75,$76,$77,$78,$79,$80,
        $81,$82,$83,$84,$85,$86,$87,$88,$89,$90,
        $91,$92,$93,$94,$95,$96)
        RETURNING *`,
        [
            data.client_id,
            data.claim_number,
            data.existing_damage,
            data.inspection_date,
            data.vehicle_repair_authorisation_document,
            data.claims_inspection_signature,
            data.claimant_signature,
            data.fault_determination,
            data.claimant_name,
            data.claimant_father_name,
            data.claimant_mother_name,
            data.claimant_birth_date,
            data.claimant_birth_place,
            data.claimant_citizenship,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_id_issued_by,
            data.claimant_license_category,
            data.claimant_license_number,
            data.claimant_license_issued_by,
            data.claimant_license_issued_date,
            data.claimant_license_experience,
            data.claimant_profession,
            data.claimant_employer,
            data.claimant_employer_address,
            data.claimant_employer_phone,
            data.claimant_employer_email,
            data.claimant_policy_series,
            data.claimant_policy_number,
            data.claimant_policy_start_date,
            data.claimant_policy_end_date,
            data.incident_date,
            data.incident_time,
            data.vehicle_registration_number,
            data.vehicle_make,
            data.vehicle_model,
            data.vehicle_color,
            data.vehicle_vin,
            data.vehicle_owner,
            data.vehicle_owner_cnp,
            data.incident_location,
            data.incident_county,
            data.incident_street,
            data.incident_direction_from,
            data.incident_direction_to,
            data.incident_place,
            data.incident_km,
            data.incident_intersection,
            data.incident_outside_of,
            data.incident_highway,
            data.incident_damages,
            data.incident_deceased,
            data.incident_other_damages,
            data.incident_deceased_name,
            data.casco_number,
            data.casco_company,
            data.casco_validity_start_date,
            data.casco_validity_end_date,
            data.light_conditions,
            data.road_conditions,
            data.weather_conditions,
            data.road_surface_type,
            data.vehicle_category,
            data.vehicle_speed,
            data.vehicle_break_mark,
            data.damage_area,
            data.other_vehicle_damage_area,
            data.diagram_before,
            data.diagram_at_time_of_incident,
            data.diagram_after,
            data.other_victim_name,
            data.other_victim_address,
            data.other_victim_property,
            data.authorities_document_series,
            data.authorities_document_number,
            data.repair_authorisation_series,
            data.repair_authorisation_number,
            data.repair_authorisation_date,
            data.incident_responsible_name,
            data.incident_responsible_address,
            data.incident_responsible_phone,
            data.incident_responsible_email,
            data.incident_responsible_vehicle_registration_number,
            data.incident_responsible_vehicle_make,
            data.incident_responsible_vehicle_model,
            data.incident_responsible_vehicle_color,
            data.incident_responsible_rca,
            data.incident_responsible_rca_series,
            data.incident_responsible_rca_number,
            data.incident_responsible_rca_validity_start_date,
            data.incident_responsible_rca_validity_end_date,
            data.claim_date,
            data.signature,
            data.created_at,
        ]
    );
    return result.rows[0];
}

export async function updateAvizareAxeria(id: string, data: types.AvizareAxeriaUpdateSchema): Promise<types.AvizareAxeria> {
    const result = await query(
        `UPDATE avizare_axeria
      SET client_id = $2,
          claim_number = $3,
          existing_damage = $4,
          inspection_date = $5,
          vehicle_repair_authorisation_document = $6,
          claims_inspection_signature = $7,
          claimant_signature = $8,
          fault_determination = $9,
          claimant_name = $10,
          claimant_father_name = $11,
          claimant_mother_name = $12,
          claimant_birth_date = $13,
          claimant_birth_place = $14,
          claimant_citizenship = $15,
          claimant_address = $16,
          claimant_cnp = $17,
          claimant_id_series = $18,
          claimant_id_number = $19,
          claimant_id_issued_by = $20,
          claimant_license_category = $21,
          claimant_license_number = $22,
          claimant_license_issued_by = $23,
          claimant_license_issued_date = $24,
          claimant_license_experience = $25,
          claimant_profession = $26,
          claimant_employer = $27,
          claimant_employer_address = $28,
          claimant_employer_phone = $29,
          claimant_employer_email = $30,
          claimant_policy_series = $31,
          claimant_policy_number = $32,
          claimant_policy_start_date = $33,
          claimant_policy_end_date = $34,
          incident_date = $35,
          incident_time = $36,
          vehicle_registration_number = $37,
          vehicle_make = $38,
          vehicle_model = $39,
          vehicle_color = $40,
          vehicle_vin = $41,
          vehicle_owner = $42,
          vehicle_owner_cnp = $43,
          incident_location = $44,
          incident_county = $45,
          incident_street = $46,
          incident_direction_from = $47,
          incident_direction_to = $48,
          incident_place = $49,
          incident_km = $50,
          incident_intersection = $51,
          incident_outside_of = $52,
          incident_highway = $53,
          incident_damages = $54,
          incident_deceased = $55,
          incident_other_damages = $56,
          incident_deceased_name = $57,
          casco_number = $58,
          casco_company = $59,
          casco_validity_start_date = $60,
          casco_validity_end_date = $61,
          light_conditions = $62,
          road_conditions = $63,
          weather_conditions = $64,
          road_surface_type = $65,
          vehicle_category = $66,
          vehicle_speed = $67,
          vehicle_break_mark = $68,
          damage_area = $69,
          other_vehicle_damage_area = $70,
          diagram_before = $71,
          diagram_at_time_of_incident = $72,
          diagram_after = $73,
          other_victim_name = $74,
          other_victim_address = $75,
          other_victim_property = $76,
          authorities_document_series = $77,
          authorities_document_number = $78,
          repair_authorisation_series = $79,
          repair_authorisation_number = $80,
          repair_authorisation_date = $81,
          incident_responsible_name = $82,
          incident_responsible_address = $83,
          incident_responsible_phone = $84,
          incident_responsible_email = $85,
          incident_responsible_vehicle_registration_number = $86,
          incident_responsible_vehicle_make = $87,
          incident_responsible_vehicle_model = $88,
          incident_responsible_vehicle_color = $89,
          incident_responsible_rca = $90,
          incident_responsible_rca_series = $91,
          incident_responsible_rca_number = $92,
          incident_responsible_rca_validity_start_date = $93,
          incident_responsible_rca_validity_end_date = $94,
          claim_date = $95,
          signature = $96,
          created_at = $97
            WHERE id = $1
            RETURNING *`,
            [
                id,
                    data.client_id,
                    data.claim_number,
                    data.existing_damage,
                    data.inspection_date,
                    data.vehicle_repair_authorisation_document,
                    data.claims_inspection_signature,
                    data.claimant_signature,
                    data.fault_determination,
                    data.claimant_name,
                    data.claimant_father_name,
                    data.claimant_mother_name,
                    data.claimant_birth_date,
                    data.claimant_birth_place,
                    data.claimant_citizenship,
                    data.claimant_address,
                    data.claimant_cnp,
                    data.claimant_id_series,
                    data.claimant_id_number,
                    data.claimant_id_issued_by,
                    data.claimant_license_category,
                    data.claimant_license_number,
                    data.claimant_license_issued_by,
                    data.claimant_license_issued_date,
                    data.claimant_license_experience,
                    data.claimant_profession,
                    data.claimant_employer,
                    data.claimant_employer_address,
                    data.claimant_employer_phone,
                    data.claimant_employer_email,
                    data.claimant_policy_series,
                    data.claimant_policy_number,
                    data.claimant_policy_start_date,
                    data.claimant_policy_end_date,
                    data.incident_date,
                    data.incident_time,
                    data.vehicle_registration_number,
                    data.vehicle_make,
                    data.vehicle_model,
                    data.vehicle_color,
                    data.vehicle_vin,
                    data.vehicle_owner,
                    data.vehicle_owner_cnp,
                    data.incident_location,
                    data.incident_county,
                    data.incident_street,
                    data.incident_direction_from,
                    data.incident_direction_to,
                    data.incident_place,
                    data.incident_km,
                    data.incident_intersection,
                    data.incident_outside_of,
                    data.incident_highway,
                    data.incident_damages,
                    data.incident_deceased,
                    data.incident_other_damages,
                    data.incident_deceased_name,
                    data.casco_number,
                    data.casco_company,
                    data.casco_validity_start_date,
                    data.casco_validity_end_date,
                    data.light_conditions,
                    data.road_conditions,
                    data.weather_conditions,
                    data.road_surface_type,
                    data.vehicle_category,
                    data.vehicle_speed,
                    data.vehicle_break_mark,
                    data.damage_area,
                    data.other_vehicle_damage_area,
                    data.diagram_before,
                    data.diagram_at_time_of_incident,
                    data.diagram_after,
                    data.other_victim_name,
                    data.other_victim_address,
                    data.other_victim_property,
                    data.authorities_document_series,
                    data.authorities_document_number,
                    data.repair_authorisation_series,
                    data.repair_authorisation_number,
                    data.repair_authorisation_date,
                    data.incident_responsible_name,
                    data.incident_responsible_address,
                    data.incident_responsible_phone,
                    data.incident_responsible_email,
                    data.incident_responsible_vehicle_registration_number,
                    data.incident_responsible_vehicle_make,
                    data.incident_responsible_vehicle_model,
                    data.incident_responsible_vehicle_color,
                    data.incident_responsible_rca,
                    data.incident_responsible_rca_series,
                    data.incident_responsible_rca_number,
                    data.incident_responsible_rca_validity_start_date,
                    data.incident_responsible_rca_validity_end_date,
                    data.claim_date,
                    data.signature,
                    data.created_at
            ]
    );

    if (result.rowCount === 0) throw new Error('Avizare Axeria not found');
    return result.rows[0];
}