import {z} from "zod";

export const avizareGroupamaCreateSchema = z.object({
    client_id: z.uuidv4(),
    claimant_name: z.string(),
    claimant_cnp: z.string(),
    claimant_id_series: z.string(),
    claimant_id_number: z.string(),
    claimant_phone: z.string(),
    claimant_email: z.string(),
    incident_type: z.string(),
    incident_date: z.string(),
    incident_time: z.string(),
    vehicle_state: z.string(),
    vehicle_make: z.string(),
    vehicle_model: z.string(),
    vehicle_registration_number: z.string(),
    vehicle_owner: z.string(),
    casco_number: z.string(),
    rca_number: z.string(),
    rca_date: z.string(),
    trailer_make: z.string(),
    trailer_type: z.string(),
    trailer_registration_number: z.string(),
    trailer_owner: z.string(),
    trailer_casco: z.string(),
    trailer_rca: z.string(),
    incident_city: z.string(),
    incident_county: z.string(),
    incident_street: z.string(),
    incident_building: z.string(),
    incident_km: z.string(),
    incident_direction_from: z.string(),
    incident_direction_to: z.string(),
    incident_description: z.string(),
    incident_damages: z.string(),
    incident_other_damages: z.boolean(),
    incident_other_damages_description: z.string(),
    police_investigation: z.boolean(),
    contravention_report_issued: z.boolean(),
    diagram: z.string(),
    at_fault_vehicle_rca_series: z.string(),
    at_fault_vehicle_rca_number: z.string(),
    at_fault_vehicle_rca_insurer: z.string(),
    at_fault_vehicle_optional_insurance: z.boolean(),
    agree_pre_reparir_payment: z.boolean(),
    claim_date: z.string(),
    signature: z.string()
})
export const avizareGroupamaUpdateSchema = avizareGroupamaCreateSchema;