import {query} from "@/db";
import * as types from "@/entities/templates/avizare-eazy/types";

export async function getAllAvizareEazy(): Promise<Array<types.AvizareEazy>> {
    const result = await query(`
        SELECT *
        FROM avizare_eazy
        ORDER BY created_at DESC
    `);
    return result.rows;
}

export async function getAvizareEazyById(id: string): Promise<types.AvizareEazy> {
    const result = await query(
        `SELECT * FROM avizare_eazy WHERE id = $1`,
        [id]
    );
    if(result.rowCount === 0) throw new Error("Avizare eazy not found");
    return result.rows[0];
}

export async function createAvizareEazy(data: types.AvizareEazyCreateSchema): Promise<types.AvizareEazy> {
    const result = await query(
        `
        INSERT INTO avizare_eazy(
        client_id,
        claimant_name,
        claimant_father_name,
        claimant_mother_name,
        claimant_birth_date,
        claimant_birth_place,
        claimant_address,
        claimant_cnp,
        claimant_id_series,
        claimant_id_number,
        claimant_id_issued_by,
        claimant_phone,
        claimant_email,
        other_victims,
        other_damages,
        other_damages_description,
        incident_date,
        incident_location,
        incident_time,
        vehicle_state,
        incident_street,
        incident_notes,
        diagram_before,
        diagram_at_time_of_incident,
        diagram_after,
        vehicle_diagram,
        vehicle_diagram_description,
        other_vehicle_diagram,
        other_vehicle_diagram_description,
        police_section,
        police_report_series,
        police_report_number,
        repair_authorisation_series,
        repair_authorisation_number,
        police_presence,
        ambulance_presence,
        towing_used,
        towing_contact_person,
        towing_company,
        towing_cost,
        photo_video,
        relationship_with_involved_party,
        related_person_name,
        relationship_type,
        at_fault_person_name,
        at_fault_person_address,
        at_fault_person_phone,
        at_fault_person_email,
        at_fault_vehicle_registration_number,
        other_details,
        claim_date,
        signature,                   
        )
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
                ,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
                ,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
                ,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
                ,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
                 ,$51,$52,$53,$54)
        RETURNING *`,
        [
            data.client_id,
            data.claimant_name,
            data.claimant_father_name,
            data.claimant_mother_name,
            data.claimant_birth_date,
            data.claimant_birth_place,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_id_issued_by,
            data.claimant_phone,
            data.claimant_email,
            data.other_victims,
            data.other_damages,
            data.other_damages_description,
            data.incident_date,
            data.incident_location,
            data.incident_time,
            data.vehicle_state,
            data.incident_street,
            data.incident_notes,
            data.diagram_before,
            data.diagram_at_time_of_incident,
            data.diagram_after,
            data.vehicle_diagram,
            data.vehicle_diagram_description,
            data.other_vehicle_diagram,
            data.other_vehicle_diagram_description,
            data.police_section,
            data.police_report_series,
            data.police_report_number,
            data.repair_authorisation_series,
            data.repair_authorisation_number,
            data.police_presence,
            data.ambulance_presence,
            data.towing_used,
            data.towing_contact_person,
            data.towing_company,
            data.towing_cost,
            data.photo_video,
            data.relationship_with_involved_party,
            data.related_person_name,
            data.relationship_type,
            data.at_fault_person_name,
            data.at_fault_person_address,
            data.at_fault_person_phone,
            data.at_fault_person_email,
            data.at_fault_vehicle_registration_number,
            data.other_details,
            data.claim_date,
            data.signature,
        ]
    );
    return result.rows[0];
}

export async function updateAvizareEazy(id: string, data: types.AvizareEazyUpdateSchema): Promise<types.AvizareEazy> {
    const result = await query(
        `UPDATE avizare_eazy
      SET client_id = $2,
          claimant_name = $3,
          claimant_father_name = $4,
          claimant_mother_name = $5,
          claimant_birth_date = $6,
          claimant_birth_place = $7,
          claimant_address = $8,
          claimant_cnp = $9,
          claimant_id_series = $10,
          claimant_id_number = $11,
          claimant_id_issued_by = $12,
          claimant_phone = $13,
          claimant_email = $14,
          other_victims = $15,
          other_damages = $16,
          other_damages_description = $17,
          incident_date = $18,
          incident_location = $19,
          incident_time = $20,
          vehicle_state = $21,
          incident_street = $22,
          incident_notes = $23,
          diagram_before = $24,
          diagram_at_time_of_incident = $25,
          diagram_after = $26,
          vehicle_diagram = $27,
          vehicle_diagram_description = $28,
          other_vehicle_diagram = $29,
          other_vehicle_diagram_description = $30,
          police_section = $31,
          police_report_series = $32,
          police_report_number = $33,
          repair_authorisation_series = $34,
          repair_authorisation_number = $35,
          police_presence = $36,
          ambulance_presence = $37,
          towing_used = $38,
          towing_contact_person = $39,
          towing_company = $40,
          towing_cost = $41,
          photo_video = $42,
          relationship_with_involved_party = $43,
          related_person_name = $44,
          relationship_type = $45,
          at_fault_person_name = $46,
          at_fault_person_address = $47,
          at_fault_person_phone = $48,
          at_fault_person_email = $49,
          at_fault_vehicle_registration_number = $50,
          other_details = $51,
          claim_date = $52,
          signature = $53
        WHERE id = $1
        RETURNING *`,
        [
            id,
            data.client_id,
            data.claimant_name,
            data.claimant_father_name,
            data.claimant_mother_name,
            data.claimant_birth_date,
            data.claimant_birth_place,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_id_issued_by,
            data.claimant_phone,
            data.claimant_email,
            data.other_victims,
            data.other_damages,
            data.other_damages_description,
            data.incident_date,
            data.incident_location,
            data.incident_time,
            data.vehicle_state,
            data.incident_street,
            data.incident_notes,
            data.diagram_before,
            data.diagram_at_time_of_incident,
            data.diagram_after,
            data.vehicle_diagram,
            data.vehicle_diagram_description,
            data.other_vehicle_diagram,
            data.other_vehicle_diagram_description,
            data.police_section,
            data.police_report_series,
            data.police_report_number,
            data.repair_authorisation_series,
            data.repair_authorisation_number,
            data.police_presence,
            data.ambulance_presence,
            data.towing_used,
            data.towing_contact_person,
            data.towing_company,
            data.towing_cost,
            data.photo_video,
            data.relationship_with_involved_party,
            data.related_person_name,
            data.relationship_type,
            data.at_fault_person_name,
            data.at_fault_person_address,
            data.at_fault_person_phone,
            data.at_fault_person_email,
            data.at_fault_vehicle_registration_number,
            data.other_details,
            data.claim_date,
            data.signature,
        ]
    );

    if(result.rowCount === 0) throw new Error("Avizare eazy not found");
    return result.rows[0];
}