import {z} from 'zod'

export const AvizareAllianzTiriacSchemaCreateSchema = z.object({
    client_id: z.uuidv4(),
    complaint_number: z.string(),
    claimant_name: z.string(),
    claimant_email: z.string(),
    claimant_mobile_phone: z.string(),
    claimant_landline_phone: z.string(),
    representing_name: z.string(),
    incident_date: z.string(),
    incident_hour: z.string(),
    location: z.string(),
    vehicle_make: z.string(),
    registration_number: z.string(),
    vin: z.string(),
    owned_by: z.string(),
    casco_number: z.string(),
    insurance_company: z.string(),
    parked_at: z.boolean(),
    driven_by: z.string(),
    material_damage: z.boolean(),
    injured: z.boolean(),
    name_of_injured: z.string(),
    party_responsible: z.string(),
    party_responsible_vehicle_make: z.string(),
    party_responsible_registration_number: z.string(),
    party_responsible_rca: z.string(),
    party_responsible_insurance_company: z.string(),
    diagram: z.string(),
    description: z.string(),
    casco: z.boolean(),
    rcs: z.boolean(),
    date: z.string(),
    signature: z.string(),
})

export const  AvizareAllianzTiriacSchemaUpdateSchema = AvizareAllianzTiriacSchemaCreateSchema;