import {query} from "@/db";
import * as types from "@/entities/templates/avizare-grawe/types";

export async function getAllAvizareGrawe(): Promise<Array<types.AvizareGrawe>>{
    const result = await query(`
        SELECT * FROM avizare_grawe
        ORDER BY created_at DESC
    `);
    return result.rows;
}

export async function createAvizareGrawe(data: types.AvizareGraweCreateSchema): Promise<types.AvizareGrawe>{
    const result = await query(
        `
        INSERT INTO avizare_grawe (
            client_id,
            existing_damages,
            presentation_date,
            presentation_time,
            inspector_signature,
            claimant_signature,
            claimant_name,
            claimant_cnp,
            claimant_phone,
            claimant_landline,
            claimant_email,
            claimant_birthplace,
            claimant_citizenship,
            claimant_id_series,
            claimant_id_number,
            claimant_id_issued_by,
            claimant_address,
            claimant_license_category,
            claimant_license_number,
            claimant_license_issued_by,
            claimant_license_issued_date,
            claimant_license_experience,
            claimant_profession,
            claimant_employer,
            claimant_employer_address,
            claimant_declaration,
            incident_date,
            incident_time,
            vehicle_registration_number,
            vehicle_make,
            vehicle_color,
            vehicle_owner,
            incident_location,
            incident_street,
            incident_direction_from,
            incident_direction_to,
            incident_place,
            incident_intersection,
            incident_outside_of,
            incident_highway,
            vehicle_damages,
            substance_use,
            other_damages,
            other_damages_description,
            police_investigation,
            existing_report,
            police_section,
            theft_date,
            theft_report_proof_number,
            theft_report_date,
            claim_date,
            signature,
            existing_rca,
            existing_rca_number,
            existing_casco,
            existing_casco_number,
            at_fault_person_name,
            at_fault_vehicle_make,
            at_fault_vehicle_model,
            at_fault_insurance_company,
            at_fault_insurance_policty_series,
            at_fault_insurance_policy_number,
            at_fault_insurance_policy_start_date,
            at_fault_insurance_policy_end_date,
            lighting_conditions,
            road_conditions,
            weather_conditions,
            road_surface_type,
            vehicle_category,
            diagram,
            other_optional_insurance,
            claimed_compensation_other_insurer,
            received_compensation_other_insurer,
            other_policy_number,
            other_insurance_company,
            other_policy_valid_from,
            other_policy_valid_to,
            repair_authorisation_series,
            repair_authorisation_number,                         
        )
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
                $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
                $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
                $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
                $41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
                $51,$52,$53,$54,$55,$56,$57,$58,$59,$60,
                $61,$62,$63,$64,$65,$66,$67,$68,$69,$70,
                $71,$72,$73,$74,$75,$76,$77,$78,$79)
        RETURNING *`,
        [
            data.client_id,
            data.existing_damages,
            data.presentation_date,
            data.presentation_time,
            data.inspector_signature,
            data.claimant_signature,
            data.claimant_name,
            data.claimant_cnp,
            data.claimant_phone,
            data.claimant_landline,
            data.claimant_email,
            data.claimant_birthplace,
            data.claimant_citizenship,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_id_issued_by,
            data.claimant_address,
            data.claimant_license_category,
            data.claimant_license_number,
            data.claimant_license_issued_by,
            data.claimant_license_issued_date,
            data.claimant_license_experience,
            data.claimant_profession,
            data.claimant_employer,
            data.claimant_employer_address,
            data.claimant_declaration,
            data.incident_date,
            data.incident_time,
            data.vehicle_registration_number,
            data.vehicle_make,
            data.vehicle_color,
            data.vehicle_owner,
            data.incident_location,
            data.incident_street,
            data.incident_direction_from,
            data.incident_direction_to,
            data.incident_place,
            data.incident_intersection,
            data.incident_outside_of,
            data.incident_highway,
            data.vehicle_damages,
            data.substance_use,
            data.other_damages,
            data.other_damages_description,
            data.police_investigation,
            data.existing_report,
            data.police_section,
            data.theft_date,
            data.theft_report_proof_number,
            data.theft_report_date,
            data.claim_date,
            data.signature,
            data.existing_rca,
            data.existing_rca_number,
            data.existing_casco,
            data.existing_casco_number,
            data.at_fault_person_name,
            data.at_fault_vehicle_make,
            data.at_fault_vehicle_model,
            data.at_fault_insurance_company,
            data.at_fault_insurance_policty_series,
            data.at_fault_insurance_policy_number,
            data.at_fault_insurance_policy_start_date,
            data.at_fault_insurance_policy_end_date,
            data.lighting_conditions,
            data.road_conditions,
            data.weather_conditions,
            data.road_surface_type,
            data.vehicle_category,
            data.diagram,
            data.other_optional_insurance,
            data.claimed_compensation_other_insurer,
            data.received_compensation_other_insurer,
            data.other_policy_number,
            data.other_insurance_company,
            data.other_policy_valid_from,
            data.other_policy_valid_to,
            data.repair_authorisation_series,
            data.repair_authorisation_number
        ]
    );
    return result.rows[0];
}

export async function getAvizareGraweById(id: string): Promise<types.AvizareGrawe>{
    const result = await query(
        `SELECT * FROM avizare_grawe WHERE id = $1`,
        [id]
    );
    if(result.rowCount === 0) throw new Error("Avizare grawe not found");
    return result.rows[0];
}

export async function updateAvizareGrawe(id: string, data: types.AvizareGraweUpdateSchema): Promise<types.AvizareGrawe>{
    const result = await query(
        `UPDATE avizare_grawe
      SET client_id = $2,
          existing_damages = $3,
          presentation_date = $4,
          presentation_time = $5,
          inspector_signature = $6,
          claimant_signature = $7,
          claimant_name = $8,
          claimant_cnp = $9,
          claimant_phone = $10,
          claimant_landline = $11,
          claimant_email = $12,
          claimant_birthplace = $13,
          claimant_citizenship = $14,
          claimant_id_series = $15,
          claimant_id_number = $16,
          claimant_id_issued_by = $17,
          claimant_address = $18,
          claimant_license_category = $19,
          claimant_license_number = $20,
          claimant_license_issued_by = $21,
          claimant_license_issued_date = $22,
          claimant_license_experience = $23,
          claimant_profession = $24,
          claimant_employer = $25,
          claimant_employer_address = $26,
          claimant_declaration = $27,
          incident_date = $28,
          incident_time = $29,
          vehicle_registration_number = $30,
          vehicle_make = $31,
          vehicle_color = $32,
          vehicle_owner = $33,
          incident_location = $34,
          incident_street = $35,
          incident_direction_from = $36,
          incident_direction_to = $37,
          incident_place = $38,
          incident_intersection = $39,
          incident_outside_of = $40,
          incident_highway = $41,
          vehicle_damages = $42,
          substance_use = $43,
          other_damages = $44,
          other_damages_description = $45,
          police_investigation = $46,
          existing_report = $47,
          police_section = $48,
          theft_date = $49,
          theft_report_proof_number = $50,
          theft_report_date = $51,
          claim_date = $52,
          signature = $53,
          existing_rca = $54,
          existing_rca_number = $55,
          existing_casco = $56,
          existing_casco_number = $57,
          at_fault_person_name = $58,
          at_fault_vehicle_make = $59,
          at_fault_vehicle_model = $60,
          at_fault_insurance_company = $61,
          at_fault_insurance_policty_series = $62,
          at_fault_insurance_policy_number = $63,
          at_fault_insurance_policy_start_date = $64,
          at_fault_insurance_policy_end_date = $65,
          lighting_conditions = $66,
          road_conditions = $67,
          weather_conditions = $68,
          road_surface_type = $69,
          vehicle_category = $70,
          diagram = $71,
          other_optional_insurance = $72,
          claimed_compensation_other_insurer = $73,
          received_compensation_other_insurer = $74,
          other_policy_number = $75,
          other_insurance_company = $76,
          other_policy_valid_from = $77,
          other_policy_valid_to = $78,
          repair_authorisation_series = $79,
          repair_authorisation_number = $80
        WHERE id = $1
        RETURNING *
        `,
        [
            id,
            data.client_id,
            data.existing_damages,
            data.presentation_date,
            data.presentation_time,
            data.inspector_signature,
            data.claimant_signature,
            data.claimant_name,
            data.claimant_cnp,
            data.claimant_phone,
            data.claimant_landline,
            data.claimant_email,
            data.claimant_birthplace,
            data.claimant_citizenship,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_id_issued_by,
            data.claimant_address,
            data.claimant_license_category,
            data.claimant_license_number,
            data.claimant_license_issued_by,
            data.claimant_license_issued_date,
            data.claimant_license_experience,
            data.claimant_profession,
            data.claimant_employer,
            data.claimant_employer_address,
            data.claimant_declaration,
            data.incident_date,
            data.incident_time,
            data.vehicle_registration_number,
            data.vehicle_make,
            data.vehicle_color,
            data.vehicle_owner,
            data.incident_location,
            data.incident_street,
            data.incident_direction_from,
            data.incident_direction_to,
            data.incident_place,
            data.incident_intersection,
            data.incident_outside_of,
            data.incident_highway,
            data.vehicle_damages,
            data.substance_use,
            data.other_damages,
            data.other_damages_description,
            data.police_investigation,
            data.existing_report,
            data.police_section,
            data.theft_date,
            data.theft_report_proof_number,
            data.theft_report_date,
            data.claim_date,
            data.signature,
            data.existing_rca,
            data.existing_rca_number,
            data.existing_casco,
            data.existing_casco_number,
            data.at_fault_person_name,
            data.at_fault_vehicle_make,
            data.at_fault_vehicle_model,
            data.at_fault_insurance_company,
            data.at_fault_insurance_policty_series,
            data.at_fault_insurance_policy_number,
            data.at_fault_insurance_policy_start_date,
            data.at_fault_insurance_policy_end_date,
            data.lighting_conditions,
            data.road_conditions,
            data.weather_conditions,
            data.road_surface_type,
            data.vehicle_category,
            data.diagram,
            data.other_optional_insurance,
            data.claimed_compensation_other_insurer,
            data.received_compensation_other_insurer,
            data.other_policy_number,
            data.other_insurance_company,
            data.other_policy_valid_from,
            data.other_policy_valid_to,
            data.repair_authorisation_series,
            data.repair_authorisation_number,
        ]
    );

    if(result.rowCount === 0) throw new Error("Avizare grawe not found");
    return result.rows[0];
}