import {query} from "@/db";
import * as types from "@/entities/templates/avizare-asirom/types";

export async function getAllAvizareAsirom(): Promise<Array<types.AvizareAsirom>> {
    const result = await query(`
        SELECT *
        FROM avizare_asirom
        ORDER BY created_at DESC
    `);
    return result.rows;
}

export async function createAvizareAsirom(data: types.AvizareAsiromCreateSchema): Promise<types.AvizareAsirom> {
    const result = await query(`
    INSERT INTO avizare_asirom (
        client_id,
        claimant_name,
        claimant_birth_date,
        claimant_address,
        claimant_cnp,
        claimant_driver_license_category,
        claimant_driver_license_number,
        claimant_driver_license_expiration_date,
        claimant_driver_license_experience,
        claimant_phone,
        claimant_email,
        representative_name,
        representative_birth_date,
        representative_address,
        representative_cnp,
        representative_driver_license_category,
        representative_driver_license_number,
        representative_driver_license_expiration_date,
        representative_driver_license_experience,
        representative_phone,
        representative_email,
        representative_of,
        incident_location,
        incident_type,
        incident_date,
        vehicle_make,
        vehicle_model,
        vehicle_registration_number,
        person_driving,
        person_driving_capacity,
        owner_damaged_vehicle,
        claim_number,
        claim_validity,
        responsible_party,
        bodily_injury,
        injured_person_name_first,
        injured_person_name_second,
        damage,
        damaged_area,
        circumstances,
        informed_services,
        service,
        service_address,
        service_phone_email,
        light_conditions,
        road_conditions,
        other_damaged_vehicles,
        damaged_vehicles_number,
        other_damages,
        other_vehicle_driver,
        diagram,
        owner_permission,
        compensation_received,
        substance_use,
        preexisting_damage,
        preexisting_damage_description,
        insurance_declaration,
        signature,
        created_at
    )
    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
            $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
            $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
            $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
            $41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
            $51,$52,$53,$54,$55,$56,$57,$58,$59,$60,
            $61,$62)
    RETURNING *`,
        [
            data.client_id,
            data.claimant_name,
            data.claimant_birth_date,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_driver_license_category,
            data.claimant_driver_license_number,
            data.claimant_driver_license_expiration_date,
            data.claimant_driver_license_experience,
            data.claimant_phone,
            data.claimant_email,
            data.representative_name,
            data.representative_birth_date,
            data.representative_address,
            data.representative_cnp,
            data.representative_driver_license_category,
            data.representative_driver_license_number,
            data.representative_driver_license_expiration_date,
            data.representative_driver_license_experience,
            data.representative_phone,
            data.representative_email,
            data.representative_of,
            data.incident_location,
            data.incident_type,
            data.incident_date,
            data.vehicle_make,
            data.vehicle_model,
            data.vehicle_registration_number,
            data.person_driving,
            data.person_driving_capacity,
            data.owner_damaged_vehicle,
            data.claim_number,
            data.claim_validity,
            data.responsible_party,
            data.bodily_injury,
            data.injured_person_name_first,
            data.injured_person_name_second,
            data.damage,
            data.damaged_area,
            data.circumstances,
            data.informed_services,
            data.service,
            data.service_address,
            data.service_phone_email,
            data.light_conditions,
            data.road_conditions,
            data.other_damaged_vehicles,
            data.damaged_vehicles_number,
            data.other_damages,
            data.other_vehicle_driver,
            data.diagram,
            data.owner_permission,
            data.compensation_received,
            data.substance_use,
            data.preexisting_damage,
            data.preexisting_damage_description,
            data.insurance_declaration,
            data.signature,
            data.created_at
        ]
    );

    return result.rows[0];
}

export async function getAvizareAsiromById(id: string): Promise<types.AvizareAsirom> {
    const result = await query(
        `SELECT * FROM avizare_asirom WHERE id = $1`,
        [id]
    );
    if(result.rowCount === 0) throw new Error("Avizare not found");
    return result.rows[0];
}

export async function updateAvizareAsirom(id: string, data: types.AvizareAsiromUpdateSchema): Promise<types.AvizareAsirom> {
    const result = await query(
        `UPDATE avizare_asirom
      SET     
              client_id = $2,
              claimant_name = $3,
              claimant_birth_date = $4,
              claimant_address = $5,
              claimant_cnp = $6,
              claimant_driver_license_category = $7,
              claimant_driver_license_number = $8,
              claimant_driver_license_expiration_date = $9,
              claimant_driver_license_experience = $10,
              claimant_phone = $11,
              claimant_email = $12,
              representative_name = $13,
              representative_birth_date = $14,
              representative_address = $15,
              representative_cnp = $16,
              representative_driver_license_category = $17,
              representative_driver_license_number = $18,
              representative_driver_license_expiration_date = $19,
              representative_driver_license_experience = $20,
              representative_phone = $21,
              representative_email = $22,
              representative_of = $23,
              incident_location = $24,
              incident_type = $25,
              incident_date = $26,
              vehicle_make = $27,
              vehicle_model = $28,
              vehicle_registration_number = $29,
              person_driving = $30,
              person_driving_capacity = $31,
              owner_damaged_vehicle = $32,
              claim_number = $33,
              claim_validity = $34,
              responsible_party = $35,
              bodily_injury = $36,
              injured_person_name_first = $37,
              injured_person_name_second = $38,
              damage = $39,
              damaged_area = $40,
              circumstances = $41,
              informed_services = $42,
              service = $43,
              service_address = $44,
              service_phone_email = $45,
              light_conditions = $46,
              road_conditions = $47,
              other_damaged_vehicles = $48,
              damaged_vehicles_number = $49,
              other_damages = $50,
              other_vehicle_driver = $51,
              diagram = $52,
              owner_permission = $53,
              compensation_received = $54,
              substance_use = $55,
              preexisting_damage = $56,
              preexisting_damage_description = $57,
              insurance_declaration = $58,
              signature = $59,
              created_at = $60
      WHERE id = $1
      RETURNING *`,
        [
            id,
            data.client_id,
            data.claimant_name,
            data.claimant_birth_date,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_driver_license_category,
            data.claimant_driver_license_number,
            data.claimant_driver_license_expiration_date,
            data.claimant_driver_license_experience,
            data.claimant_phone,
            data.claimant_email,
            data.representative_name,
            data.representative_birth_date,
            data.representative_address,
            data.representative_cnp,
            data.representative_driver_license_category,
            data.representative_driver_license_number,
            data.representative_driver_license_expiration_date,
            data.representative_driver_license_experience,
            data.representative_phone,
            data.representative_email,
            data.representative_of,
            data.incident_location,
            data.incident_type,
            data.incident_date,
            data.vehicle_make,
            data.vehicle_model,
            data.vehicle_registration_number,
            data.person_driving,
            data.person_driving_capacity,
            data.owner_damaged_vehicle,
            data.claim_number,
            data.claim_validity,
            data.responsible_party,
            data.bodily_injury,
            data.injured_person_name_first,
            data.injured_person_name_second,
            data.damage,
            data.damaged_area,
            data.circumstances,
            data.informed_services,
            data.service,
            data.service_address,
            data.service_phone_email,
            data.light_conditions,
            data.road_conditions,
            data.other_damaged_vehicles,
            data.damaged_vehicles_number,
            data.other_damages,
            data.other_vehicle_driver,
            data.diagram,
            data.owner_permission,
            data.compensation_received,
            data.substance_use,
            data.preexisting_damage,
            data.preexisting_damage_description,
            data.insurance_declaration,
            data.signature,
            data.created_at
        ]
    );

    if(result.rowCount === 0) throw new Error("Avizare not found");
    return result.rows[0];
}