import {query} from "@/db";
import * as types from "@/entities/templates/avizare-dallbog/types";

export async function getAllAvizareDallbog(): Promise<Array<types.AvizareDallbog>> {
    const result = await query(`
        SELECT *
        FROM avizare_dallbog
        ORDER BY created_at DESC
    `);
    return result.rows;
}

export async function createAvizareDallbog(data: types.AvizareDallbogCreateSchema): Promise<types.AvizareDallbog> {
    const result = await query(
        `
        INSERT INTO avizare_dallbog (
            client_id,
            existing_damaged_vehicle,
            claim_date,
            claim_time,
            claim_series,
            claim_number,
            claim_inspector_signature,
            claimant_signature,
            claimant_name,
            claimant_father_name,
            claimant_mother_name,
            claimant_birth_date,
            claimant_birth_place,
            claimant_citizenship,
            claimant_address,
            claimant_cnp,
            claimant_id_series,
            claimant_id_number,
            claimant_license_category,
            claimant_license_number,
            claimant_license_issued_by,
            claimant_license_issued_date,
            claimant_license_experience,
            claimant_profession,
            claimant_employer,
            claimant_employer_phone,
            incident_date,
            incident_time,
            vehicle_state,
            vehicle_registration_number,
            vehicle_make_model,
            vehicle_color,
            vehicle_owner,
            incident_location,
            incident_street,
            incident_direction_from,
            incident_direction_to,
            incident_place,
            incident_intersection,
            incident_outside_of,
            incident_highway,
            vehicle_damages,
            existing_casco,
            casco_company,
            casco_validity_end_date,
            light_conditions,
            road_conditions,
            vehicle_category,
            past_damages,
            diagram,
            signature,
                                     )
        VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 
                $11, $12, $13, $14, $15, $16, $17, $18,
                $19, $20, $21, $22, $23, $24, $25, $26, $27,
                $28, $29, $30, $31, $32, $33, $34, $35, $36,
                $37, $38, $39, $40, $41, $42, $43, $44, $45,
                $46, $47, $48, $49, $50, $51
                )
        RETURNING *`,
    [
        data.client_id,
        data.existing_damaged_vehicle,
        data.claim_date,
        data.claim_time,
        data.claim_series,
        data.claim_number,
        data.claim_inspector_signature,
        data.claimant_signature,
        data.claimant_name,
        data.claimant_father_name,
        data.claimant_mother_name,
        data.claimant_birth_date,
        data.claimant_birth_place,
        data.claimant_citizenship,
        data.claimant_address,
        data.claimant_cnp,
        data.claimant_id_series,
        data.claimant_id_number,
        data.claimant_license_category,
        data.claimant_license_number,
        data.claimant_license_issued_by,
        data.claimant_license_issued_date,
        data.claimant_license_experience,
        data.claimant_profession,
        data.claimant_employer,
        data.claimant_employer_phone,
        data.incident_date,
        data.incident_time,
        data.vehicle_state,
        data.vehicle_registration_number,
        data.vehicle_make_model,
        data.vehicle_color,
        data.vehicle_owner,
        data.incident_location,
        data.incident_street,
        data.incident_direction_from,
        data.incident_direction_to,
        data.incident_place,
        data.incident_intersection,
        data.incident_outside_of,
        data.incident_highway,
        data.vehicle_damages,
        data.existing_casco,
        data.casco_company,
        data.casco_validity_end_date,
        data.light_conditions,
        data.road_conditions,
        data.vehicle_category,
        data.past_damages,
        data.diagram,
        data.signature,
        ]
    );

    return result.rows[0];
}

export async function getAvizareDallbogById(id: string): Promise<types.AvizareDallbog> {
    const result = await query(
        `SELECT * FROM avizare_dallbog WHERE id = $1`,
        [id]
    );
    if(result.rowCount === 0) throw new Error("Avizare dallbog not found");
    return result.rows[0];
}

export async function updateAvizareDallbog(id: string, data: types.AvizareDallbogUpdateSchema): Promise<types.AvizareDallbog> {
    const result = await query(
        `UPDATE avizare_dallbog
      SET client_id = $2,
          existing_damaged_vehicle = $3,
          claim_date = $4,
          claim_time = $5,
          claim_series = $6,
          claim_number = $7,
          claim_inspector_signature = $8,
          claimant_signature = $9,
          claimant_name = $10,
          claimant_father_name = $11,
          claimant_mother_name = $12,
          claimant_birth_date = $13,
          claimant_birth_place = $14,
          claimant_citizenship = $15,
          claimant_address = $16,
          claimant_cnp = $17,
          claimant_id_series = $18,
          claimant_id_number = $19,
          claimant_license_category = $20,
          claimant_license_number = $21,
          claimant_license_issued_by = $22,
          claimant_license_issued_date = $23,
          claimant_license_experience = $24,
          claimant_profession = $25,
          claimant_employer = $26,
          claimant_employer_phone = $27,
          incident_date = $28,
          incident_time = $29,
          vehicle_state = $30,
          vehicle_registration_number = $31,
          vehicle_make_model = $32,
          vehicle_color = $33,
          vehicle_owner = $34,
          incident_location = $35,
          incident_street = $36,
          incident_direction_from = $37,
          incident_direction_to = $38,
          incident_place = $39,
          incident_intersection = $40,
          incident_outside_of = $41,
          incident_highway = $42,
          vehicle_damages = $43,
          existing_casco = $44,
          casco_company = $45,
          casco_validity_end_date = $46,
          light_conditions = $47,
          road_conditions = $48,
          vehicle_category = $49,
          past_damages = $50,
          diagram = $51,
          signature = $52
    WHERE id = $1
    RETURNING *
        `,
        [
            id,
            data.client_id,
            data.existing_damaged_vehicle,
            data.claim_date,
            data.claim_time,
            data.claim_series,
            data.claim_number,
            data.claim_inspector_signature,
            data.claimant_signature,
            data.claimant_name,
            data.claimant_father_name,
            data.claimant_mother_name,
            data.claimant_birth_date,
            data.claimant_birth_place,
            data.claimant_citizenship,
            data.claimant_address,
            data.claimant_cnp,
            data.claimant_id_series,
            data.claimant_id_number,
            data.claimant_license_category,
            data.claimant_license_number,
            data.claimant_license_issued_by,
            data.claimant_license_issued_date,
            data.claimant_license_experience,
            data.claimant_profession,
            data.claimant_employer,
            data.claimant_employer_phone,
            data.incident_date,
            data.incident_time,
            data.vehicle_state,
            data.vehicle_registration_number,
            data.vehicle_make_model,
            data.vehicle_color,
            data.vehicle_owner,
            data.incident_location,
            data.incident_street,
            data.incident_direction_from,
            data.incident_direction_to,
            data.incident_place,
            data.incident_intersection,
            data.incident_outside_of,
            data.incident_highway,
            data.vehicle_damages,
            data.existing_casco,
            data.casco_company,
            data.casco_validity_end_date,
            data.light_conditions,
            data.road_conditions,
            data.vehicle_category,
            data.past_damages,
            data.diagram,
            data.signature,
        ]
    );

    if(result.rowCount === 0) throw new Error("Avizare dallbog not found");
    return result.rows[0];
}