import {z} from 'zod'

export const AvizareEazySchemaCreateSchema = z.object({
    client_id: z.uuidv4(),
    claimant_name: z.string(),
    claimant_father_name: z.string(),
    claimant_mother_name: z.string(),
    claimant_birth_date: z.string(),
    claimant_birth_place: z.string(),
    claimant_address: z.string(),
    claimant_cnp: z.string(),
    claimant_id_series: z.string(),
    claimant_id_number: z.string(),
    claimant_id_issued_by: z.string(),
    claimant_phone: z.string(),
    claimant_email: z.string(),
    other_victims: z.boolean(),
    other_damages: z.boolean(),
    other_damages_description: z.string(),
    incident_date: z.string(),
    incident_location: z.string(),
    incident_time: z.string(),
    vehicle_state: z.string(),
    incident_street: z.string(),
    incident_notes: z.string(),
    diagram_before: z.string(),
    diagram_at_time_of_incident: z.string(),
    diagram_after: z.string(),
    vehicle_diagram: z.string(),
    vehicle_diagram_description: z.string(),
    other_vehicle_diagram: z.string(),
    other_vehicle_diagram_description: z.string(),
    police_section: z.string(),
    police_report_series: z.string(),
    police_report_number: z.string(),
    repair_authorisation_series: z.string(),
    repair_authorisation_number: z.string(),
    police_presence: z.string(),
    ambulance_presence: z.string(),
    towing_used: z.boolean(),
    towing_contact_person: z.string(),
    towing_company: z.string(),
    towing_cost: z.string(),
    photo_video: z.boolean(),
    relationship_with_involved_party: z.boolean(),
    related_person_name: z.string(),
    relationship_type: z.string(),
    at_fault_person_name: z.string(),
    at_fault_person_address: z.string(),
    at_fault_person_phone: z.string(),
    at_fault_person_email: z.string(),
    at_fault_vehicle_registration_number: z.string(),
    other_details: z.string(),
    date: z.string(),
    signature: z.string(),
})

export const  AvizareEazySchemaUpdateSchema = AvizareEazySchemaCreateSchema;