import {z} from 'zod'

export const AvizareOmniasigSchemaCreateSchema = z.object({
    client_id: z.uuidv4(),
    claimant_name: z.string(),
    claimant_birth_date: z.string(),
    claimant_address: z.string(),
    claimant_cnp: z.string(),
    claimant_driver_license_category: z.string(),
    claimant_driver_license_number: z.string(),
    claimant_driver_license_expiration_date: z.string(),
    claimant_driver_license_experience: z.string(),
    claimant_phone: z.string(),
    claimant_email: z.string(),
    representative_name: z.string(),
    representative_birth_date: z.string(),
    representative_address: z.string(),
    representative_cnp: z.string(),
    representative_driver_license_category: z.string(),
    representative_driver_license_number: z.string(),
    representative_driver_license_expiration_date: z.string(),
    representative_driver_license_experience: z.string(),
    representative_phone: z.string(),
    representative_email: z.string(),
    representative_of: z.string(),
    incident_location: z.string(),
    incident_type: z.string(),
    incident_date: z.string(),
    vehicle_make: z.string(),
    vehicle_model: z.string(),
    vehicle_registration_number: z.string(),
    person_driving: z.string(),
    person_driving_capacity: z.string(),
    owner_damaged_vehicle: z.string(),
    claim_number: z.string(),
    claim_validity: z.string(),
    responsible_party: z.string(),
    bodily_injury: z.boolean(),
    injured_person_name_first: z.string(),
    injured_person_name_second: z.string(),
    damage: z.string(),
    damaged_area: z.string(),
    circumstances: z.string(),
    informed_services: z.string(),
    service: z.string(),
    service_address: z.string(),
    service_phone_email: z.string(),
    light_conditions: z.string(),
    road_conditions: z.string(),
    other_damaged_vehicles: z.boolean(),
    damaged_vehicles_number: z.string(),
    other_damages: z.string(),
    other_vechicle_driver: z.string(),
    diagram: z.string(),
    owner_permision: z.boolean(),
    compensation_received: z.boolean(),
    substance_use: z.boolean(),
    preexisting_damage: z.boolean(),
    preexisting_damage_description: z.string(),
    insurance_declaration: z.boolean(),
    signature: z.string(),
})

export const  AvizareOmniasigSchemaUpdateSchema = AvizareOmniasigSchemaCreateSchema;